spring:
  cloud:
    config:
      server:
#        native:
#            search-locations: classpath:/shared
        git:
          searchPaths: config/src/main/resources/shared
          uri: https://github.com/biaoYoo/YooTransport/
          username: biaoYoo
          password: Yu332404
      label: master
#  profiles:
#    active: native
  application:
    name: config-server
  rabbitmq:
    host: 120.76.62.168
    port: 5672
    username: guest
    password: guest

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:1100/eureka/  # 指定服务注册中心的地址


security:
  user:
   name: yoo
   password: yu123

management:
  security:
    enabled: false

server:
  port: 8888


