server:
  port: 1100
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  serviceUrl:
    defaultZone: http://127.0.0.1:${server.port}/eureka/

security:
  user:
   name: yoo
   password: yu123
