server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.11:yu123@127.0.0.1:1100/eureka/  # 指定服务注册中心的地址

zuul:
  routes:
    provider-capacity:
      path: /provider-capacity/**
      serviceId: provider-capacity
    provider-order:
      path: /provider-order/**
      serviceId: provider-order
    provider-user:
      path: /provider-user/**
      serviceId: provider-user


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
