spring:
  rabbitmq:
     host: 120.76.62.168
     port: 5672
     username: guest
     password: guest

server:
  port: 1100

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  serviceUrl:
    defaultZone: http://120.76.62.168:${server.port}/eureka/
